version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/marmara
    volumes:
      - ./uploaded_files:/app/uploaded_files


  celery:
    build: .
    command: celery -A celery_worker.celery worker --loglevel=info
    depends_on:
      - redis
      - web
    volumes:
      - ./uploaded_files:/app/uploaded_files


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: marmara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
