version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/marmara
    volumes:
      - ./uploaded_files:/app/uploaded_files

  celery_audio_worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info -Q audio --concurrency=2
    depends_on:
      - redis
      - web
    volumes:
      - ./uploaded_files:/app/uploaded_files

  celery_llm_worker:
    build: .
    command: celery -A app.tasks.celery_app worker --loglevel=info -Q llm --concurrency=1
    depends_on:
      - redis
      - web


  redis:
    image: redis:7
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: marmara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
